Add inotify instance limit info
vector-im/element-web pull request #15795
Opened 2020-11-23 07:54 UTC by SimonBrandner

I've added inotify instance limit info based on: these issues [#15750](https://github.com/vector-im/element-web/issues/15750), [#15774](https://github.com/vector-im/element-web/issues/15774) and this StackOverflow [question](https://stackoverflow.com/questions/64919108/error-emfile-too-many-open-files-watch-unless-i-use-sudo/64941113#64941113).

2020-11-23 16:07 UTC, jryans requested changes
Thanks, overall this looks good. Just a few tweaks that would be good to add.

2020-11-23 16:07 UTC, jryans commented on README.md
> +[#15774](https://github.com/vector-im/element-web/issues/15774).
```suggestion
You may be interested in issues [#15750](https://github.com/vector-im/element-web/issues/15750) and
[#15774](https://github.com/vector-im/element-web/issues/15774) for further details.
```

2020-11-23 16:07 UTC, jryans commented on README.md
> +echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
This is a pre-existing issue, but may as well clean it up here. The watches value is different from the previous block:

```suggestion
echo fs.inotify.max_user_watches=131072 | sudo tee -a /etc/sysctl.conf
```

2020-11-23 18:46 UTC, SimonBrandner commented
I am sorry that I forgot the sign-off.

Signed-off-by: Šimon Brandner simon.bra.ag@gmail.com

2020-11-24 11:25 UTC, jryans approved these changes
Looks great, thanks for the contribution!

2020-11-24 11:25 UTC, merged