document giphy integration
vector-im/element-web pull request #16808
Opened 2021-03-28 18:49 UTC by panoschal

2021-05-09 18:41 UTC, SimonBrandner commented
@panoschal, I think the merge broke your PR :P 
![Screenshot_20210509_204042](https://user-images.githubusercontent.com/25768714/117583319-de27c300-b106-11eb-8218-35aa7455702f.png)

2021-05-22 16:48 UTC, tsukasagenesis commented
If someone can look into it

2021-06-30 16:34 UTC, t3chguy requested changes
Needs DCO sign-off (see https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.rst#sign-off) and the tests passing

2021-08-19 05:58 UTC, Palid commented
Is this still relevant? @panoschal
New sign-off link: https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md#sign-off

2021-08-19 06:09 UTC, SimonBrandner commented
> Is this still relevant? @panoschal

Definitely, the react-sdk PR is waiting for design/product review though, so this is quite stuck... Perhaps someone could give them a nudge

2021-08-19 12:03 UTC, SimonBrandner requested changes

2021-08-19 12:03 UTC, SimonBrandner commented on docs/labs.md
> +Associated PR: https://github.com/matrix-org/matrix-react-sdk/pull/5814
I don't think we usually link to a specific PR. You might do some follow up PRs and it doesn't really make sense to link them all here. What we usually do though is link the PR in this PR's description

2021-08-19 12:08 UTC, SimonBrandner commented
Your CI is failing because it using _your_ develop branches from the other layers. You'll have to merge and push on these too

2021-08-19 12:20 UTC, SimonBrandner approved these changes
LGTM - thanks!

2021-08-19 12:30 UTC, panoschal commented
Great! I signed in the PR description.

2021-08-19 12:32 UTC, SimonBrandner commented
Marking as blocked since the react-sdk PR hasn't been merged yet

2023-04-27 10:13 UTC, t3chguy commented
The associated PR this was for got closed

2023-04-27 10:13 UTC, closed without merging