Added `feature_thread`
vector-im/element-web pull request #20761
Opened 2022-01-26 07:31 UTC by eleensmathew

Most of the information is from https://github.com/matrix-org/matrix-doc/blob/gsouquet/threading-via-relations/proposals/3440-threading-via-relations.md. Please review and tell me if any changes are to be made.

2022-01-26 10:01 UTC, gsouquet requested changes
Thank you for opening a PR here.
The idea is to document the feature at a very high level so that folks understand roughly what it does.

For this pull request to be merged I would recommend you remove all technical details and write a few lines describing what this does

2022-01-26 10:27 UTC, eleensmathew commented on docs/labs.md
> +Thread-ready clients would recieve the latest event in the thread unless a user is explicitly replying to another event.
## Threaded Messaging (`feature_thread`)

Threading allows users to branch out a new conversation from the main timeline of a room. This is particularly useful in high traffic rooms where multiple conversations can happen in parallel or when a single discussion might stretch over a very long period of time.

Clients should fill in the new field (https://github.com/matrix-org/matrix-doc/blob/gsouquet/threading-via-relations/proposals/3440-threading-via-relations.md#backwards-compatibility) in order to display that in a thread context.
When a thread head is aggregated (as in MSC2675), it returns a summary of the thread: the latest message, a list of participants and the total count of messages.
A thread will be displayed as a chain of replies on clients unaware of threads.
Thread-ready clients would receive the latest event in the thread unless a user is explicitly replying to another event.

Clients can also synthesize read receipts but it is possible that some notifications get lost on a fresh start.

2022-01-26 10:30 UTC, eleensmathew commented on docs/labs.md
> +Thread-ready clients would recieve the latest event in the thread unless a user is explicitly replying to another event.
>Is this okay?? should I remove the link and not include the  'fill the feild' part? Also should i remove the (As in MSC2675) part as well?

2022-03-01 19:32 UTC, rriemann commented on docs/labs.md
> +Thread-ready clients would recieve the latest event in the thread unless a user is explicitly replying to another event.
Is it OK @gsouquet ?

2022-03-02 09:25 UTC, gsouquet requested changes

2022-03-02 09:25 UTC, gsouquet commented on docs/labs.md
> +Clients can synthesize read receipts but it is possible that some notifications get lost on a fresh start.
```suggestion
Threading allows users to branch out a new conversation from the main timeline of a room. This is particularly useful in high traffic rooms where multiple conversations can happen in parallel or when a single discussion might stretch over a very long period of time.

Threads can be access by clicking their summary below the root event on the room timeline. Users can find a comprehensive list of threads by click the icon on the room header button.

This feature might work in degraded mode if the homeserver a user is connected to does not advertise support for the unstable feature `org.matrix.msc3440`  when calling the `/versions` API endpoint.
```

2022-03-02 09:26 UTC, gsouquet commented
It looks like this PR needs rebasing too, there's some conflicting file

2022-03-04 05:21 UTC, eleensmathew commented
Hi @gsouquet  I changed the file as you suggested, but I opened a new pull request https://github.com/vector-im/element-web/pull/21303 to fix the issues.

2022-03-04 08:26 UTC, gsouquet commented
Closing in favour of https://github.com/vector-im/element-web/pull/21303

2022-03-04 08:26 UTC, closed without merging