Show spell check settings on macOS
vector-im/element-web pull request #22220
Opened 2022-05-16 14:14 UTC by SimonBrandner

For https://github.com/matrix-org/matrix-react-sdk/pull/8604
Notes: none

2022-05-16 20:36 UTC, turt2live requested changes
this needs a bit of context - there's claims on the linked issues that we can't reasonably manage spell check for mac OS, hence the check. 

Evidence to the contrary would be nice :)

2022-05-17 05:45 UTC, SimonBrandner commented
> this needs a bit of context - there's claims on the linked issues that we can't reasonably manage spell check for mac OS, hence the check.
> 
> Evidence to the contrary would be nice :)

The method had a rather unideal name :/

2022-05-17 05:46 UTC, turt2live approved these changes
bonus points if all the functions here get their public/private/protected declarations

2022-05-17 06:03 UTC, SimonBrandner commented
https://github.com/vector-im/element-web/issues/22235 :P

2022-06-26 22:59 UTC, turt2live approved these changes

2022-07-13 09:32 UTC, t3chguy approved these changes
LGTM otherwise

2022-07-13 09:32 UTC, t3chguy commented on src/vector/platform/ElectronPlatform.tsx
> +    setSpellCheckLanguages(preferredLangs: string[]): void {
this lost a `public`

```suggestion
    public setSpellCheckLanguages(preferredLangs: string[]): void {
```

2022-07-28 08:19 UTC, merged