Add GHA for Dead Code Analysis
vector-im/element-web pull request #22830
Opened 2022-07-13 09:04 UTC by SimonBrandner

2022-07-29 21:48 UTC, turt2live requested changes
unclear why this is blocked

2022-07-30 06:20 UTC, SimonBrandner commented
See https://github.com/vector-im/element-web/issues/21969#issuecomment-1193823688

2022-08-04 16:11 UTC, robintown approved these changes

2022-08-04 16:34 UTC, turt2live approved these changes

2022-08-04 16:34 UTC, merged