Add Element Call participant limit
vector-im/element-web pull request #23431
Opened 2022-10-05 18:56 UTC by SimonBrandner

Requires https://github.com/matrix-org/matrix-react-sdk/pull/9358

2022-10-06 19:27 UTC, turt2live reviewed
the sample config doesn't really do anything other than documentation - was this supposed to change the nightly & develop configs?

2022-10-07 04:18 UTC, SimonBrandner commented
> the sample config doesn't really do anything other than documentation - was this supposed to change the nightly & develop configs?

Since we setup defaults and I assume we'd want to use those on nightly & develop, the change sample config is only documentation

2022-10-07 04:28 UTC, turt2live requested changes
this should be documented in https://github.com/vector-im/element-web/blob/develop/docs/config.md then, not in the sample config

2022-10-07 17:37 UTC, robintown approved these changes

2022-10-07 18:24 UTC, turt2live approved these changes

2022-10-07 20:00 UTC, merged