Bump @matrix-org/react-sdk-module-api to 0.0.4
vector-im/element-web pull request #24642
Opened 2023-02-24 12:42 UTC by andybalaam

This gives access to the new widget customisations e.g. https://github.com/matrix-org/matrix-react-sdk/pull/10121

2023-03-01 10:27 UTC, maheichyk commented
@andybalaam it seems that the pipeline should be fine if restarted, so maybe could try to merge

2023-03-01 10:52 UTC, t3chguy requested changes
Seems like no bumping actually happened given no yarn.lock change

2023-03-01 12:22 UTC, andybalaam commented
Good point @t3chguy . After much fighting with `yarn install` trying to prevent the wrong matrix-events-sdk version re-appearing, I realised I needed https://github.com/vector-im/element-web/pull/24708 first, then I can fix this one.

2023-03-01 14:34 UTC, t3chguy requested changes

2023-03-01 14:34 UTC, t3chguy commented on yarn.lock
> +  resolved "https://codeload.github.com/matrix-org/matrix-react-sdk/tar.gz/4f1e5a71dec65258f5295f7d60d2e733391d304c"
This looks wrong.

2023-03-02 14:24 UTC, t3chguy approved these changes

2023-03-02 14:30 UTC, andybalaam commented
Still getting this, something is still not right with the lockfile:

```
[current branch] Install Dependencies
  Installing using yarn --frozen-lockfile
  /usr/local/bin/yarn --frozen-lockfile
  yarn install v1.22.19
  [1/4] Resolving packages...
  error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
  info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
  Error: The process '/usr/local/bin/yarn' failed with exit code 1
```

2023-03-02 16:20 UTC, andybalaam commented
I can't understand why I'm still getting:

```
/usr/local/bin/yarn --frozen-lockfile
  yarn install v1.22.19
  [1/4] Resolving packages...
  error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
```

After my latest commit did a `yarn install` and that command works for me locally.

2023-03-02 16:24 UTC, andybalaam commented
Ah, I think it's running against a different commit so it can compare with this one.

Given that the main Static Analysis action passed, I think this PR is fine. Merging and keeping an eye in case I'm wrong.

2023-03-02 16:24 UTC, merged