Add options to mute audio and/or video in Jitsi calls by default
vector-im/element-web pull request #24820
Opened 2023-03-14 16:18 UTC by dhenneke

We have the use case that we don't want to activate the video and/or audio of Jitsi participants by default. There is the `isAudioOnly` flag, but that has some side effects, like that a joining user must activate their camera before being able to see others who have their camera activated (hence "audio only").

This PR proposes to add flags for both the [`startWithAudioMuted`](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-configuration/#startwithaudiomuted) and [`startWithVideoMuted`](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-configuration/#startwithvideomuted) configs. These settings can be set when adding the jitsi widget to a room (we do that with a bot for example).

Requires the following PR in the matrix-react-sdk: 

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/vector-im/element-web/blob/develop/CONTRIBUTING.md))

2023-03-14 18:10 UTC, jakewb-b approved these changes
From a product point of view, this all seems good. Thanks.

2023-03-15 07:23 UTC, weeman1337 requested changes
The changelog item reads like there is an option I can choose as a user. What it actually does is to add an API for that.

Probably something like „Add API params to mute audio and/or video in Jitsi calls by default “ would be better.

Looks good otherwise :+1:

2023-03-15 08:47 UTC, dhenneke commented
@weeman1337 thanks for the feedback. I updated both PRs with the changed name and also updated the PR titles to improve the changelog entry.

2023-03-15 12:49 UTC, weeman1337 approved these changes
Tested with a local build. Works :+1:

2023-03-15 12:50 UTC, merged